### ISSUE TITLE
How to disable on Mobile / Tablet?

### ISSUE THREAD

**Issue by maheshwaghmare** [bbarakaci/fixto#44]
Is there any option to disable `fixto` on mobile / tablet devices.

Tried custom solution as below:

```
var ww = $(window).outerWidth();
if( ww > 769 ) {
    $('.stick-this').fixTo('#page', {
        className : 'stick-this-active',
        zIndex: 100,
        top: 0,
        useNativeSticky: false
    });
} else {
    // $('.stick-this').fixTo('hide');
    // $('.stick-this').fixTo('refresh');
    $('.stick-this').fixTo('destroy');
}
```

But not working!!!

---

What `_destroy` doing? It's found twice?

https://github.com/bbarakaci/fixto/blob/master/src/fixto.js#L610
https://github.com/bbarakaci/fixto/blob/master/src/fixto.js#L390

Any solution??

**Comment by bbarakaci** [comment]
If you get rid of the else statement, it should be fine. You will be
initializing only when the requirement is met.

**Comment by maheshwaghmare** [comment]
Thanks @bbarakaci for the quick response.

I initialize fixto above the `768` ( Which is my requirement ). But, It still fixes the section on resize( Below 768px ). Just for information.

One last question:
Is there any future scope to enable / disable fixto on mobile devices?

Except this, it's working awesome.

**Comment by maheshwaghmare** [comment]
I'm closing this issue now ( Not issue It's future enhancement may be).

**Comment by bbarakaci** [comment]
once it is initialized, it will be there. mobile devices will not resize the page after the page load so you will be fine fine.

if you want to destroy it on resize, then you have to check and do it on every resize event, and it will got tricky because you should not reinitialize or you can't destroy something that is not initialized.

Maybe you would like to check mobile detection libraries like 

https://github.com/hgoebl/mobile-detect.js
https://github.com/kaimallea/isMobile

There will be no such feature. These kind implementations are up to developer.
